Repository Intro-to-SE-lab-Spring-22/Group-1, pull requests merged in 2022-03, with the labels that each got.

#15 Working on Timeline Functions
  models/postmodel.js
  routes/post.js
Labels: bug

#18 Core feature 1 & core feature 3
  api/models/posts.model.js
  api/models/users.model.js
  api/routes/post.js
Labels: added functions for Core Feature 2

#26 Adding documentation
  Documentation/42146214_LabGuideline-Spring-2022.pdf
  Documentation/Group1_SRS.pdf
  Documentation/Project Topic.pdf
Labels: documentation

#21 Core feature 2
  react/src/components/post/post.css
  react/src/components/post/post.jsx
  react/src/components/share/share.jsx
  react/src/components/timeline/timeline.jsx
Labels: bug, added functions for Core Feature 2
